version: "3"
services:
  ngrok-iiw:
    image: wernight/ngrok
    command: ngrok http iiw-agent:${IIW_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  iiw-agent:
    build:
      context: ../../
      dockerfile: projects/iiw/Dockerfile.agent
    environment:
      NGROK_NAME: ngrok-iiw
      AGENT_NAME: ${IIW_AGENT_NAME}
      HTTP_PORT: ${IIW_HTTP_PORT}
      ADMIN_PORT: ${IIW_ADMIN_PORT}
      WEBHOOK_URL: ${IIW_WEBHOOK_URL}
      API_KEY: ${IIW_API_KEY}
    ports:
      - ${IIW_HTTP_PORT}:${IIW_HTTP_PORT}
      - ${IIW_ADMIN_PORT}:${IIW_ADMIN_PORT}
    networks:
      - indy_demo
    volumes:
      - iiw-agent:/home/indy/.indy_client/default
  iiw-notebook:
    build:
      context: ../../
      dockerfile: projects/iiw/Dockerfile
      args:
        - jupyter_port=${JUPYTER_PORT}
    depends_on:
      - iiw-agent
    networks:
      - indy_demo
    volumes:
      - ./notebooks:/workspace
    ports:
      - "8888:8888"
      - ${IIW_WEBHOOK_PORT}:${IIW_WEBHOOK_PORT}
volumes:
  iiw-agent:
networks:
  indy_demo:
