name: 'Run black linting'

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  PythonLinting:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Black Python linting
        uses: lgeiger/black-action@master
        with:
          args: . --check